name: docker-hub

on:
  push:
    branches: main

jobs:
  login-build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: install buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest

      - name: Build and push
        run: |
          docker buildx build --tag ${{ secrets.DOCKERHUB_USERNAME }}/nats-gui --platform linux/amd64,linux/arm/v7,linux/arm64 .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/nats-gui:latest
